title: FedLab
email: dirg@umu.se
description: >
  A test suite for identity federation protocols, OAuth, OpenID Connect and SAML
baseurl: "/feed-lab.org" # the subpath of your site, e.g. /blog
url: "http://fed-lab.org" # the base hostname & protocol for your site

# Footer Settings
credit: Theme by <a href="https://themehall.com/">ThemeHall</a>

exclude: 
  - Gemfile
  - Gemfile.lock

# Build settings
markdown: kramdown
